default:
  key: default
  driver: simple # We could have used also (default, bcrypt, SSL any other?

debug:
  key: debug-key
  driver: simpl

admin:
  key: admin
  driver: simple

user:
  key: user
  driver: simple

# Test
