# 200: "Success"
# 301: "Moved permanently"

BAD_REQUEST:
  message: "Bad request"
  status: 400

REQUEST_TOO_LARGE:
  message: "Request too large"
  status: 413

REQUEST_TOO_LONG:
  message: "Requested uri too long"
  status: 414

UPGRADE_REQUIRED:
  message: "Upgrade required"
  status: 426

TOO_MANY_REQUESTS:
  message: "Too many requests"
  status: 429

INTERNAL_UNDEFINED:
  message: 'Internal server error'
  status: 500

UNDEFINED_ROUTE:
  message: "Route not found/implemented"
  status: 501

BAD_GATEWAY:
  message: "Bad gateway"
  status: 502

SERVICE_UNAVAILABLE:
  message: "Service Unavailable"
  status: 503

TIMEOUT:
  message: "Gateway Timeout"
  status: 504

ROUTE_DEFINITION:
  message: "Route expects method and route, `{GET|PUT|PATCH|DELETE} {PATH}`. Example: `GET /user/v1/:test`"
  status: 500

MIDDLEWARE_HANDLER:
  message: "`%s` in middleware handler (%s), at line `%s`"
  status: 500

UNDEFINED_ACCESS:
  message: "Access (%s) not defined in `config/access.yaml`"
  status: 500

ACCESS_UNDEFINED_DRIVER:
  message: "Access driver (%s) not found in `access`."
  status: 500

ACCESS_DRIVER_CONSTRUCTOR:
  message: "Could not construct driver (%s). Reason: %s"
  status: 500

ACCESS_AUTHORIZE:
  message: "Access async `authorize` definition required in `%s`"
  status: 500

ACCESS_AUTHORITY:
  message: "Access `authorize` return result required to be `async` or `Promise` in `%s`"
  status: 500

ACCESS_AUTHORITY_EXCEPTION:
  message: "Access `authorize` (%s) thrown `%s`"
  status: 500

VALIDATION_REQUIRE_VALUE:
  message: "Validation requires value (%s)"
  status: 500

MIN_LENGTH_REQUIRED:
  message: "Bad argument `%s` length. Required more than %n"
  status: 500

MAX_LENGTH_REQUIRED:
  message: "Bad argument `%s` length. Required less than %n"
  status: 500

VALIDATION_REGEX_MISMATCH:
  message: "Value (%s) is invalid"
  status: 500

MIDDLEWARE_RESULT:
  message: "Expected a promise result in `%s`"
  status: 500

MIDDLEWARE_EXCEPTION:
  message: "Exception occured when processing middleware: %s"
  status: 500

MIDDLEWARE_NOT_DEFINED:
  message: "Middleware `%s` not defined or not AsyncFunction or Promise"
  status: 500

REQUEST_BAD_FIELD:
  message: "Request body includes undefined data (%s)"
  status: 500

BAD_AUTHORIZATION:
  message: "Authorization missmatch"
  status: 500

UNDEFINED_STORAGE_DRIVER:
  message: "Undefined storage driver (%s)"
  status: 500

BAD_YAML_FILE:
  message: "Could not load YAML file `%s`. Reason: %s"
  status: 500

STORAGE_DEFAULT_PUT:
  message: "Default Storage.put(key, value, expires_in) function. Requires a overload in storage driver constructor!"
  status: 500

STORAGE_DEFAULT_GET:
  message: "Default Storage.get(key, value) function. Requires a overload in storage driver constructor!"
  status: 500

STORAGE_DEFAULT_PATCH:
  message: "Default Storage.patch(key, value) function. Requires a overload in storage driver constructor!"
  status: 500

STORAGE_DEFAULT_INVALIDATE:
  message: "Default Storage.invalidate(key) function. Requires a overload in storage driver constructor!"
  status: 500

STORAGE_DEFAULT_EXPIRE:
  message: "Default Storage.expire(key, expires_in) function. Requires a overload in storage driver constructor!"
  status: 500

CACHE_RESULT:
  message: "Expected a Promise result from Storage.get in cache middleware"
  status: 500

VALIDATON_ERROR:
  message: "Validation `%s` failed. Schema `%s`, %s"
  status: 500

ACCESS_EXCEPTION:
  message: "Access exception: %s"
  status: 500

ROUTE_ACTION_REQUIRED:
  message: "Route requires {QUERY|MIDDLEWARE} definition"
  status: 500

UNDEFINED_CONNECTION:
  message: "Connection `%s` is undefined"
  status: 500

UNDEFINED_METHOD:
  message: "Undefined %s in `%s`"
  status: 500

MISSING_CONFIGURATION_FILE:
  message: "Configuration file missing `%s`"
  status: 500

CONFIGURATION_FILE_EXCEPTION:
  message: "Configuration (%s) exception `%s`"
  status: 500

DUPLICATED_CONFIGURATION:
  message: "Duplicated configuration (%s) found `%s`"
  status: 500

# 512 - 597 Free status for specific errors?
